pkl_dir_path             = 'pickles'
train_val_df_pkl_path    = 'train_val_df.pickle'
test_df_pkl_path         = 'test_df.pickle'
qualification_df_pkl_path= 'qualification_df.pickle'
backup_df_pkl_path       = 'backup_df.pickle'
disease_classes_pkl_path = 'disease_classes.pickle'
models_dir               = 'models'